apiVersion: apps/v1
kind: Deployment
metadata:
  name: animeproc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animeproc
  template:
    metadata:
      labels:
        app: animeproc
    spec:
      containers:
        - name: animecon
          image: secloud007/animerepo:animeimage
          ports:
            - containerPort: 9090
